# Generated by Django 4.1.7 on 2024-10-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('satuan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('beverages', 'Beverages'), ('dishes', 'Dishes'), ('dessert', 'Dessert')], max_length=10, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('bahan_baku', models.ManyToManyField(null=True, to='posapp.bahanbaku')),
            ],
        ),
        migrations.CreateModel(
            name='TableQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('table_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('order_type', models.CharField(choices=[('online', 'Online'), ('dine-in', 'Dine-In')], max_length=10, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('atas_nama', models.CharField(max_length=255, null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('cart', 'Cart')], max_length=10, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='BahanBakuPerMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bahan_baku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posapp.bahanbaku')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posapp.menuitem')),
            ],
        ),
    ]
