# Generated by Django 4.1.7 on 2024-10-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_invoice_total_harga_remove_invoice_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
