# Generated by Django 4.1.7 on 2024-10-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
